## Basics

### Creating Arrays

✅ Great question!
NumPy provides **many ways to create arrays**, each useful for different situations. Here’s a neat summary:

---

## 🚀 **1. From Python data structures**

### ➡️ `np.array`

Create an array directly from a Python list, tuple or nested lists.


In [4]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])
a,b

(array([1, 2, 3]),
 array([[1, 2],
        [3, 4]]))


---

## 🚀 **2. Arrays filled with constants**

### ➡️ `np.zeros`

Creates an array filled with zeros.


In [6]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])


### ➡️ `np.ones`

Creates an array filled with ones.


In [8]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])



### ➡️ `np.full`

Creates an array filled with a specified value.


In [10]:
np.full((2, 2), 7)

array([[7, 7],
       [7, 7]])


### ➡️ `np.empty`

Creates an array without initializing entries (values are garbage).


In [12]:
np.empty((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])



---

## 🚀 **3. Sequences of numbers**

### ➡️ `np.arange`

Like Python’s `range` but returns an array.


In [14]:
np.arange(0, 10, 2)  # array([0, 2, 4, 6, 8])


array([0, 2, 4, 6, 8])

### ➡️ `np.linspace`

Generates `n` evenly spaced samples between start and stop.

In [10]:
np.linspace(0, 2, 5)  # array([0. , 0.25, 0.5, 0.75, 1. ])


array([0. , 0.5, 1. , 1.5, 2. ])

---

## 🚀 **4. Random arrays**

### ➡️ `np.random.rand`

Uniform distribution over \[0, 1).

In [2]:
import numpy as np
np.random.rand(3, 2)  # shape 3x2

array([[0.2963395 , 0.91152799],
       [0.19427674, 0.49172625],
       [0.30044653, 0.89109961]])

### ➡️ `np.random.randn`

Samples from standard normal distribution.


In [21]:
np.random.randn(3)

array([0.0186303 , 0.47281761, 0.80042548])


### ➡️ `np.random.randint`

Random integers from low (inclusive) to high (exclusive).


In [12]:
np.random.randint(0, 10, size=(2, 3))

array([[0, 9, 0],
       [8, 9, 4]])

---

## 🚀 **5. Identity and eye matrices**

### ➡️ `np.eye`

Creates a 2-D array with ones on the diagonal.


In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])


### ➡️ `np.identity`

Similar, explicitly for identity matrices.


In [14]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])


---

## 🚀 **6. Other advanced creations**

### ➡️ `np.fromfunction`

Create array by executing a function over coordinate grid.


In [15]:
np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])


### ➡️ `np.fromiter`

Creates array from any iterable.


In [19]:
np.fromiter(range(5), dtype=int)


array([0, 1, 2, 3, 4])


### ➡️ `np.frombuffer`

Interprets a buffer (like bytes) as a 1-D array.


In [20]:
np.frombuffer(b'hello', dtype='S1')

array([b'h', b'e', b'l', b'l', b'o'], dtype='|S1')

In [22]:
import numpy as np

identity_matrix = np.eye(3)
diagonal_array = np.diag([1, 2, 3])
zeros_like_array = np.zeros_like(diagonal_array)
ones_like_array = np.ones_like(diagonal_array)

print(identity_matrix)
print(diagonal_array)
print(zeros_like_array)
print(ones_like_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]



---

## ✅ **Quick cheatsheet table**

| Method                   | Example use                             |
| ------------------------ | --------------------------------------- |
| `np.array`               | From Python list/tuple                  |
| `np.zeros` / `np.ones`   | Filled with 0s / 1s                     |
| `np.full`                | Filled with any constant                |
| `np.empty`               | Uninitialized (fast, random data)       |
| `np.arange`              | Like `range`, returns array             |
| `np.linspace`            | Evenly spaced samples                   |
| `np.random.rand`         | Uniform random floats                   |
| `np.random.randn`        | Normal distribution                     |
| `np.random.randint`      | Random integers                         |
| `np.eye` / `np.identity` | Identity matrix                         |
| `np.fromfunction`        | Array from applying function to indices |
| `np.fromiter`            | From any iterable                       |
| `np.frombuffer`          | From binary data                        |

---

🎯 **If you want**, I can give you:

* A small **code snippet example** for each type, all together in one file
* Or a **PDF cheatsheet** with this summary

Just tell me what format you’d like! 🚀