# 🚀 1️⃣ Array creation

| Function              | What it does             | Example                         |
| --------------------- | ------------------------ | ------------------------------- |
| `np.array()`          | From Python lists/tuples | `np.array([1,2,3])`             |
| `np.zeros()`          | All zeros                | `np.zeros((2,3))`               |
| `np.ones()`           | All ones                 | `np.ones((2,3))`                |
| `np.full()`           | All fill value           | `np.full((2,3), 7)`             |
| `np.eye()`            | Identity matrix          | `np.eye(3)`                     |
| `np.arange()`         | Like `range` but array   | `np.arange(0,10,2)`             |
| `np.linspace()`       | Evenly spaced numbers    | `np.linspace(0,1,5)`            |
| `np.random.randn()`   | Standard normal          | `np.random.randn(3,4)`          |
| `np.random.randint()` | Random ints              | `np.random.randint(0,10,(3,4))` |

---

# 🚀 2️⃣ Reshaping and modifying shape

| Function               | What it does          | Example                     |
| ---------------------- | --------------------- | --------------------------- |
| `.reshape()`           | Change shape          | `a.reshape(3,4)`            |
| `.flatten()`           | To 1D array           | `a.flatten()`               |
| `.ravel()`             | Similar, often faster | `a.ravel()`                 |
| `np.expand_dims()`     | Add axis              | `np.expand_dims(a, axis=0)` |
| `np.squeeze()`         | Remove single-dim     | `np.squeeze(a)`             |
| `.transpose()` or `.T` | Swap axes             | `a.T`                       |

---

# 🚀 3️⃣ Indexing, slicing, boolean masking

| What               | Example           |
| ------------------ | ----------------- |
| Basic slicing      | `a[1:3, 2:4]`     |
| Boolean indexing   | `a[a > 0.5]`      |
| Fancy indexing     | `a[[0,2], [1,3]]` |
| Set values by mask | `a[a<0] = 0`      |

---

# 🚀 4️⃣ Aggregations (statistics, summaries)

| Function                            | What it does       | Example                |
| ----------------------------------- | ------------------ | ---------------------- |
| `np.sum()`                          | Sum of elements    | `np.sum(a)`            |
| `np.mean()`                         | Mean               | `np.mean(a, axis=0)`   |
| `np.std()` / `np.var()`             | Std / variance     | `np.std(a)`            |
| `np.min()` / `np.max()`             | Min / max          | `np.max(a, axis=1)`    |
| `np.argmin()` / `np.argmax()`       | Indices of min/max | `np.argmax(a, axis=1)` |
| `np.percentile()` / `np.quantile()` | Quantiles          | `np.percentile(a, 90)` |

---

# 🚀 5️⃣ Arithmetic operations & broadcasting

✅ NumPy does **element-wise operations** by default.

| Example      | Explanation              |
| ------------ | ------------------------ |
| `a + b`      | Adds arrays element-wise |
| `a * 2`      | Scales each element      |
| `np.sqrt(a)` | Square root              |
| `np.exp(a)`  | Exponential              |
| `np.log(a)`  | Natural log              |
| `np.abs(a)`  | Absolute value           |
| Broadcasting | `a + 3`, `a + [1,2,3]`   |

---

# 🚀 6️⃣ Linear algebra (matrix math)

| Function           | What it does             | Example             |
| ------------------ | ------------------------ | ------------------- |
| `np.dot()` or `@`  | Matrix multiplication    | `a @ b`             |
| `np.matmul()`      | Matrix multiplication    | `np.matmul(a, b)`   |
| `np.linalg.inv()`  | Inverse                  | `np.linalg.inv(A)`  |
| `np.linalg.det()`  | Determinant              | `np.linalg.det(A)`  |
| `np.linalg.eig()`  | Eigenvalues/vectors      | `np.linalg.eig(A)`  |
| `np.linalg.svd()`  | Singular value decompos. | `np.linalg.svd(A)`  |
| `np.linalg.qr()`   | QR decomposition         | `np.linalg.qr(A)`   |
| `np.linalg.norm()` | Norm                     | `np.linalg.norm(a)` |

---

# 🚀 7️⃣ Random sampling & distributions

| Function                  | What it does                 | Example                         |
| ------------------------- | ---------------------------- | ------------------------------- |
| `np.random.seed()`        | Set seed for reproducibility | `np.random.seed(42)`            |
| `np.random.rand()`        | Uniform \[0,1)               | `np.random.rand(3,4)`           |
| `np.random.randn()`       | Standard normal              | `np.random.randn(1000)`         |
| `np.random.randint()`     | Random ints                  | `np.random.randint(0,10,(5,5))` |
| `np.random.choice()`      | Random sample                | `np.random.choice([1,2,3], 5)`  |
| `np.random.permutation()` | Shuffle                      | `np.random.permutation(10)`     |

---

# 🚀 8️⃣ Saving & loading data

| Function       | What it does       | Example                                    |
| -------------- | ------------------ | ------------------------------------------ |
| `np.save()`    | Save to `.npy`     | `np.save('array.npy', a)`                  |
| `np.load()`    | Load `.npy` file   | `b = np.load('array.npy')`                 |
| `np.savetxt()` | Save to text/csv   | `np.savetxt('file.csv', a, delimiter=',')` |
| `np.loadtxt()` | Load from text/csv | `np.loadtxt('file.csv', delimiter=',')`    |

---

# 🚀 9️⃣ Utilities & checks

| Function                     | What it does    | Example            |
| ---------------------------- | --------------- | ------------------ |
| `np.unique()`                | Unique elements | `np.unique(a)`     |
| `np.sort()` / `np.argsort()` | Sort / indices  | `np.sort(a)`       |
| `np.isnan()`                 | Check NaNs      | `np.isnan(a)`      |
| `np.isfinite()`              | Check finite    | `np.isfinite(a)`   |
| `np.clip()`                  | Clip to bounds  | `np.clip(a, 0, 1)` |

---

# 🚀 10️⃣ Broadcasting mechanics

✅ Understand how arrays automatically stretch in shape:



```python
a = np.array([[1], [2], [3]])  # shape (3,1)
b = np.array([10, 20, 30])     # shape (3,)
c = a + b                      # shape (3,3)
```



---

# ⚡ Quick cheatsheet summary


In [47]:
import numpy as np

# Arrays
a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])
c = a + b

print("c = a + b:\n", c)

# Creation
print("Zeros:\n", np.zeros((2,3)))
print("Ones:", np.ones(4))
print("Eye:\n", np.eye(3))
print("Arange:", np.arange(10))
print("Linspace:", np.linspace(0,1,5))

# Stats
print("Mean:", np.mean(a))
print("Std:", np.std(a))
print("Var:", np.var(a))
print("Sum:", np.sum(a))
print("Median:", np.median(a))

# Shape operations
print("Reshape (using tile to match size):\n", np.tile(a, (1,2)))  # example
print("Flatten:", a.flatten())
print("Transpose:\n", a.T)

# Indexing
print("Element a[1,0]:", a[1,0])
print("Slice a[1:3, :]:\n", a[1:3, :])
print("Mask a[a>0]:", a[a>0])

# Linalg
A = np.array([[2,1],[7,4]])  # ensure square for inv
print("Dot product:", np.dot(a.flatten(), b))
print("Inverse:\n", np.linalg.inv(A))
print("SVD:", np.linalg.svd(A))

# Random
print("Random normal:\n", np.random.randn(3,4))
print("Random int:", np.random.randint(0,10,5))

# Save and Load
np.save('file.npy', a)
loaded = np.load('file.npy')
print("Loaded from file.npy:\n", loaded)


c = a + b:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones: [1. 1. 1. 1.]
Eye:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Arange: [0 1 2 3 4 5 6 7 8 9]
Linspace: [0.   0.25 0.5  0.75 1.  ]
Mean: 2.0
Std: 0.816496580927726
Var: 0.6666666666666666
Sum: 6
Median: 2.0
Reshape (using tile to match size):
 [[1 1]
 [2 2]
 [3 3]]
Flatten: [1 2 3]
Transpose:
 [[1 2 3]]
Element a[1,0]: 2
Slice a[1:3, :]:
 [[2]
 [3]]
Mask a[a>0]: [1 2 3]
Dot product: 140
Inverse:
 [[ 4. -1.]
 [-7.  2.]]
SVD: SVDResult(U=array([[-0.26693358, -0.96371493],
       [-0.96371493,  0.26693358]]), S=array([8.36574631, 0.11953506]), Vh=array([[-0.87019991, -0.49269881],
       [-0.49269881,  0.87019991]]))
Random normal:
 [[ 0.04637488  1.36795714  2.64890593  0.69911548]
 [ 0.77163968 -0.45638308  0.17692049  0.08363571]
 [-1.16523384 -0.23382105  0.57953308  0.39261839]]
Random int: [6 4 2 0 5]
Loaded from file.npy:
 [[1]
 [2]
 [3]]


✅ Absolutely!
That’s a **fantastic idea** — many data scientists stop at the basics, but mastering **intermediate & advanced NumPy APIs** makes you **faster, more memory-efficient, and ready for big data problems**.

---

## 🚀 Let's go beyond basics:

I’ll divide this into:

```
1️⃣ Intermediate APIs (for power array manipulations)
2️⃣ Advanced APIs (for performance, broadcasting tricks, memory, and advanced linear algebra)
```

With **short examples** for each.

---

# 🚀 1️⃣ Intermediate NumPy APIs

---

## 📌 a) `np.where`

Conditional element selection.


In [48]:
a = np.array([1, 2, 3, 4])
np.where(a > 2, 10, 0)  # => [0, 0, 10, 10]

array([ 0,  0, 10, 10])


---

## 📌 b) `np.meshgrid`

Create coordinate grids (used for contour plots, 3D surfaces, etc).



In [49]:
x = np.linspace(0,1,5)
y = np.linspace(0,1,3)
X, Y = np.meshgrid(x, y)
print(X,'and',y)

[[0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]] and [0.  0.5 1. ]



---

## 📌 c) `np.tile` and `np.repeat`

Repeat arrays in patterns.



In [50]:
np.tile([1,2], 3)      # [1 2 1 2 1 2]
np.repeat([1,2], 3)    # [1 1 1 2 2 2]

array([1, 1, 1, 2, 2, 2])



---

## 📌 d) `np.argsort` and `np.argpartition`

For partial sorting (fast).



In [51]:
a = np.array([9, 3, 7, 1])
np.argsort(a)         # full sort indices
np.argpartition(a, 2) # indices with element at 2nd position sorted, rest unordered


array([3, 1, 2, 0])


---

## 📌 e) `np.diff` and `np.gradient`

Useful for time series or signals.



In [52]:
np.diff([1,3,6,10])    # differences: [2 3 4]
np.gradient([1,3,6,10]) # approximate derivative


array([2. , 2.5, 3.5, 4. ])



---

## 📌 f) `np.histogram` (for binning data)


In [53]:
data = np.random.randn(1000)
counts, bins = np.histogram(data, bins=10)




---

## 📌 g) `np.bincount`

Count frequency of integers (super fast histogram for integer labels).



In [54]:
labels = np.array([1,2,2,3,3,3])
np.bincount(labels)  # => [0,1,2,3]


array([0, 1, 2, 3])



---

## 📌 h) `np.cumsum`, `np.cumprod`

Cumulative operations.



In [55]:
np.cumsum([1,2,3])  # [1,3,6]
np.cumprod([1,2,3]) # [1,2,6]


array([1, 2, 6])



---

## 📌 i) `np.unique` with `return_counts`


In [56]:

arr = np.array([1,2,2,3,3,3])
np.unique(arr, return_counts=True)  # (array([1,2,3]), array([1,2,3]))



(array([1, 2, 3]), array([1, 2, 3]))


---

## 📌 j) `np.insert`, `np.delete`

Manipulate contents by position.



In [57]:

a = np.array([1,2,3])
np.insert(a, 1, 10)  # [1,10,2,3]
np.delete(a, 1)      # [1,3]


array([1, 3])



---

# 🚀 2️⃣ Advanced NumPy APIs

---

## 📌 a) Memory-efficient: `np.view` and `np.copy`



In [58]:

a = np.arange(6).reshape(2,3)
b = a.view()
b[0,0] = 99
# changes 'a' as well because it's a view




Use `b = a.copy()` for independent data.

---

## 📌 b) `np.einsum`

Einstein summation — extremely powerful.

Examples:



In [59]:

a = np.array([1,2,3])
b = np.array([0,1,0])
np.einsum('i,i->', a, b)  # dot product

M = np.arange(9).reshape(3,3)
np.einsum('ii->', M)      # trace (sum of diagonals)


np.int64(12)



This can also replace `np.dot`, `np.outer`, etc — very compact.

---

## 📌 c) Broadcasting with `np.newaxis`



In [60]:

a = np.array([1,2,3])       # shape (3,)
b = a[:, np.newaxis]         # shape (3,1)
c = a + b                    # shape (3,3)




---

## 📌 d) Masked arrays: `np.ma`

Handle missing data elegantly.


In [61]:
import numpy.ma as ma
data = ma.array([1,2,3,-1], mask=[0,0,0,1])
data.mean()  # ignores masked (-1)


np.float64(2.0)


---

## 📌 e) `np.vectorize` for quick ufunc-like operations



In [62]:
def myfunc(x):
    return x ** 2 if x > 0 else 0

vfunc = np.vectorize(myfunc)
vfunc(np.array([-2, -1, 0, 1, 2]))  # [0,0,0,1,4]


array([0, 0, 0, 1, 4])



---

## 📌 f) Advanced linear algebra (`np.linalg`)



In [63]:
B = np.random.randn(3,3)
C = np.dot(B.T, B)


In [64]:
b = np.array([10, 20, 30])
A = np.array([[2,1], [7,4]])
b = np.array([[3,6], [10,2]])

print(A)
print(np.linalg.matrix_rank(A))    # matrix rank
print(np.linalg.solve(A, b))       # solve Ax = b
print(np.linalg.cholesky(C))       # Cholesky decomposition
print(np.linalg.eigh(A))          # symmetric matrix eigen

print(A)
# print(b)


[[2 1]
 [7 4]]
2
[[  2.  22.]
 [ -1. -38.]]
[[ 1.23092929  0.          0.        ]
 [ 0.29803684  0.47225053  0.        ]
 [ 0.83441875 -1.0322321   0.17886883]]
EighResult(eigenvalues=array([-4.07106781, 10.07106781]), eigenvectors=array([[-0.75545395,  0.65520174],
       [ 0.65520174,  0.75545395]]))
[[2 1]
 [7 4]]


In [65]:
A = np.array([[2,1],[1,2]])  # symmetric and positive definite
B = np.random.randn(3,3)
A = np.dot(B.T, B)  # s



---

## 📌 g) `np.pad` for convolution prep or image borders



In [66]:
a = np.array([[1,2],[3,4]])
np.pad(a, pad_width=1, mode='constant', constant_values=0)


array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 0, 0, 0]])



---

## 📌 h) Structured arrays & recarrays (like DataFrame-lite)


In [67]:
dt = np.dtype([('name', 'S10'), ('age', 'i4')])
x = np.array([('Alice', 25), ('Bob', 30)], dtype=dt)
x['age']



array([25, 30], dtype=int32)


---

## 📌 i) `np.memmap` for huge files (won’t load full into RAM)


In [68]:
fp = np.memmap('bigdata.dat', dtype='float32', mode='w+', shape=(10000,10000))
fp[0,0] = 42


OSError: [Errno 22] Invalid argument: 'bigdata.dat'


---


# 🚀 🚀 Summary table: Intermediate & Advanced

| API                                | Purpose                        |
| ---------------------------------- | ------------------------------ |
| `np.where`, `np.select`            | Conditional array ops          |
| `np.meshgrid`, `np.mgrid`          | Grids for plots, vector fields |
| `np.tile`, `np.repeat`             | Repeat patterns                |
| `np.diff`, `np.gradient`           | Derivative & changes           |
| `np.histogram`, `np.bincount`      | Frequency analysis             |
| `np.cumsum`, `np.cumprod`          | Running totals                 |
| `np.insert`, `np.delete`           | Insert/delete by index         |
| `np.view`, `np.copy`               | Memory management              |
| `np.einsum`                        | Compact tensor operations      |
| `np.newaxis` / `[..., np.newaxis]` | Smart broadcasting             |
| `np.vectorize`                     | Apply python funcs over arrays |
| `np.linalg.svd`, `solve`, `eigh`   | Advanced algebra               |
| `np.ma`                            | Handle missing data            |
| `np.pad`                           | Convolution/image prep         |
| `np.memmap`                        | Out-of-core arrays             |

---

✅ ✅ **Done!**

If you want, I can generate:

* 🚀 A **single cheat sheet notebook** demonstrating **ALL these with short examples**.
* Or a **PDF summary**.

👉 Just tell me:

> **“Yes, give me the complete notebook!”**
> and I’ll prepare it for you. 🚀
