<a href="https://colab.research.google.com/github/svgoudar/My-Data-Science-Roadmap/blob/main/Pandas_and_Numpy/Numpy/100_numpy_exercises_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [32]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [33]:
print(np.__version__)
np.show_config()

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

#### 3. Create a null vector of size 10 (★☆☆)

In [34]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [35]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [36]:
np.info(np)

NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly t

In [37]:
!python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [38]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [39]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [40]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [41]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [42]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [43]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [44]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.00947722 0.64545661 0.00791105]
  [0.18060262 0.27075602 0.47217471]
  [0.10227524 0.57202677 0.6827652 ]]

 [[0.51122893 0.0871621  0.76236399]
  [0.05007362 0.63672645 0.95758705]
  [0.98047168 0.24048802 0.73936377]]

 [[0.30594897 0.49258467 0.05641886]
  [0.88134409 0.1225537  0.99023079]
  [0.24854929 0.00526175 0.66713496]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [45]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.01843629545661718 0.9936951210855355


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [46]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5260039445404787


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [47]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [48]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

In [49]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [50]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [51]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [52]:
print(np.unravel_index(100,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(4))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [53]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [54]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 0.47991087  0.48146779  0.08879722  1.67146081  1.97732684]
 [ 0.17374928 -1.16597534 -0.13021122 -1.00040119  0.37392288]
 [-0.11136923 -1.36628565  0.61396629  1.65845988 -1.50186678]
 [ 0.36766832 -0.02032114  1.34337399 -0.16406472 -0.24670677]
 [ 0.42450243 -1.81829965 -0.45200365 -0.1707742  -1.50632707]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [55]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [56]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [57]:
# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)

In [58]:
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

In [59]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: Integers to negative integer powers are not allowed.

Let’s go through each of these expressions assuming `Z` is an **integer vector**, like a NumPy array:

```python
import numpy as np
Z = np.array([1, 2, 3])
```

---

### ✅ 1. `Z**Z`

**Legal:** Yes
Performs element-wise exponentiation.

```python
Z**Z  # → array([1**1, 2**2, 3**3]) = array([1, 4, 27])
```

---

### ✅ 2. `2 << Z >> 2`

**Legal:** Yes
Bitwise left shift and then right shift, element-wise.

```python
2 << Z      # [2 << 1, 2 << 2, 2 << 3] = [4, 8, 16]
(2 << Z) >> 2  # [4>>2, 8>>2, 16>>2] = [1, 2, 4]
```

---

### ❌ 3. `Z <- Z`

**Illegal:** **SyntaxError in Python**
`<-` is not a valid operator in Python. That’s an R-style assignment operator.
If you meant assignment, use `Z = Z` or in-place operation like `Z[:] = Z`.

---

### ✅ 4. `1j*Z`

**Legal:** Yes
Multiplies the vector with complex number `1j`.

```python
1j * Z  # array([0.+1.j, 0.+2.j, 0.+3.j])
```

---

### ✅ 5. `Z/1/1`

**Legal:** Yes
Divides each element by 1, then again by 1.

```python
Z / 1 / 1  # → array([1., 2., 3.])
```

---

### ❌ 6. `Z<Z>Z`

**Illegal:** **SyntaxError or ambiguous expression**
Python doesn’t allow chained comparisons with NumPy arrays like this.

```python
Z < Z > Z  # Invalid, will raise ValueError or not behave as expected
```

If you want to check each pairwise condition, split it:

```python
(Z < Z) & (Z > Z)  # Will work element-wise, but gives all False
```

---

### ✅ Summary

| Expression    | Legal? | Reason                     |
| ------------- | ------ | -------------------------- |
| `Z**Z`        | ✅      | Element-wise power         |
| `2 << Z >> 2` | ✅      | Bitwise shifts             |
| `Z <- Z`      | ❌      | Invalid syntax in Python   |
| `1j*Z`        | ✅      | Complex multiplication     |
| `Z/1/1`       | ✅      | Valid chained division     |
| `Z<Z>Z`       | ❌      | Invalid chained comparison |

Let me know if you'd like this with real code examples.


#### 28. What are the result of the following expressions?

In [66]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipython-input-66-3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipython-input-66-3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipython-input-66-3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [67]:
# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(Z)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[-6.43223702  6.51081446 -2.12328802 -4.88653049  4.64033196  8.01686469
  2.00492678 -2.58128821 -3.64205626  2.13846001]
[-7.  7. -3. -5.  5.  9.  3. -3. -4.  3.]


In [87]:
np.abs(-1.69008284)

np.float64(1.69008284)

#### 30. How to find common values between two arrays? (★☆☆)

In [88]:
Z1 = np.random.randint(0,10,10)
print(Z1)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[4 7 2 0 4 0 2 4 0 3]
[0 2 4 7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [89]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)

In [70]:
np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipython-input-70-244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [71]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [72]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [94]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
print(A)
print(B)
print(C)
np.add(A,B,out=B)
print(B)
np.divide(A,2,out=A)
print(A)
np.negative(A,out=A)
print(A)
np.multiply(A,B,out=A)
print(A)

[1. 1. 1.]
[2. 2. 2.]
[3. 3. 3.]
[3. 3. 3.]
[0.5 0.5 0.5]
[-0.5 -0.5 -0.5]
[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [95]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[3. 1. 1. 7. 9. 1. 0. 1. 3. 1.]
[3. 1. 1. 7. 9. 1. 0. 1. 3. 1.]
[3. 1. 1. 7. 9. 1. 0. 1. 3. 1.]
[3 1 1 7 9 1 0 1 3 1]
[3. 1. 1. 7. 9. 1. 0. 1. 3. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [96]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [76]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [98]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [100]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.00267409 0.11522651 0.22246262 0.29316384 0.32931646 0.43913539
 0.49804566 0.82148766 0.85424299 0.87987644]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [102]:
# Author: Evgeni Burovski

Z = np.arange(10)
np.add.reduce(Z)

np.int64(45)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [103]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [104]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [105]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.8835623  0.75918384 0.80258105 1.00910645 0.92119762 0.45181616
 1.16410996 0.48977915 0.5172506  0.78257588]
[0.56705691 1.08757595 1.3942327  0.38671826 0.17470536 1.29348883
 0.65373002 1.3119203  1.00349636 0.50162316]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [112]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)
Z.argmax()

[0.12174386 0.14269779 0.03998168 0.         0.39957042 0.75350595
 0.36644926 0.18350268 0.34566997 0.7409442 ]


np.int64(5)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [113]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [117]:
# Author: Evgeni Burovski

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [118]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [120]:
# np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [121]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

84


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [122]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[(([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [84]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.59795679 0.35550602 0.33214854 0.75057162 0.47036088
  0.55059888 0.29654258 0.55866647 0.74328111]
 [0.59795679 0.         0.8162597  0.58255797 0.53960773 0.44886232
  0.69258095 0.65873124 0.43523821 0.55017071]
 [0.35550602 0.8162597  0.         0.68654231 0.71188037 0.46879394
  0.90317588 0.16402079 0.9002323  0.69650012]
 [0.33214854 0.58255797 0.68654231 0.         0.94695491 0.69501079
  0.21953163 0.61845205 0.30330299 0.94594302]
 [0.75057162 0.53960773 0.71188037 0.94695491 0.         0.28133765
  1.12844117 0.56926343 0.93169675 0.02032027]
 [0.47036088 0.44886232 0.46879394 0.69501079 0.28133765 0.
  0.89343308 0.31030195 0.74226315 0.2731041 ]
 [0.55059888 0.69258095 0.90317588 0.21953163 1.12844117 0.89343308
  0.         0.83783587 0.28715782 1.12982196]
 [0.29654258 0.65873124 0.16402079 0.61845205 0.56926343 0.31030195
  0.83783587 0.         0.78899703 0.5557555 ]
 [0.55866647 0.43523821 0.9002323  0.30330299 0.93169675 0.74226315
  0.28715782 0.78899

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [85]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)

In [86]:
from io import StringIO

# Fake file
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [123]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [124]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [125]:
# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [126]:
# Author: Warren Weckesser

X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[-0.12895074  0.01276691  0.02045107  0.01431532  0.22247391  0.14270516
  -0.27647659  0.27041097 -0.02761026 -0.25008574]
 [ 0.14347791 -0.18996259 -0.57356549  0.3270447   0.26539186  0.17609598
  -0.1028167   0.12347607  0.13964684 -0.3087886 ]
 [ 0.42105529 -0.0915553  -0.37432272  0.20018916 -0.20892745  0.15135784
  -0.2115281   0.417944   -0.10251161 -0.2017011 ]
 [ 0.27036183 -0.03552913 -0.12401632 -0.30018193  0.11675775  0.17770537
   0.23908274 -0.12627152 -0.32704062  0.10913185]
 [-0.247711    0.25399444 -0.29422473 -0.23593903 -0.09827004  0.08995825
  -0.27800948  0.16461324  0.28859809  0.35699026]]


#### 59. How to sort an array by the nth column? (★★☆)

In [127]:
# Author: Steve Tjoa

Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[8 7 3]
 [6 2 8]
 [3 7 3]]
[[6 2 8]
 [8 7 3]
 [3 7 3]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [128]:
# Author: Warren Weckesser

Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [129]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.6019546323037445


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [130]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [131]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [132]:
# Author: Brett Olsen

Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[3. 1. 3. 2. 3. 4. 3. 3. 4. 4.]
[5. 1. 5. 3. 5. 7. 5. 5. 7. 7.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [133]:
# Author: Alan G Isaac

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [134]:
# Author: Nadav Horesh

w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first.
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

OverflowError: Python integer 65536 out of bounds for uint8

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [150]:
A = np.random.randint(0,10,(3,4,3,4))
A

array([[[[5, 7, 7, 9],
         [4, 0, 3, 0],
         [8, 6, 3, 9]],

        [[6, 1, 0, 5],
         [4, 0, 7, 4],
         [0, 4, 0, 6]],

        [[9, 6, 8, 5],
         [6, 4, 6, 6],
         [3, 7, 4, 1]],

        [[5, 0, 0, 9],
         [3, 5, 7, 9],
         [1, 6, 8, 4]]],


       [[[4, 3, 9, 5],
         [5, 3, 0, 5],
         [9, 8, 1, 1]],

        [[7, 2, 2, 4],
         [5, 9, 0, 9],
         [9, 5, 2, 4]],

        [[2, 7, 4, 0],
         [6, 3, 7, 6],
         [8, 0, 5, 2]],

        [[8, 5, 0, 0],
         [0, 4, 0, 9],
         [3, 3, 5, 4]]],


       [[[6, 3, 8, 6],
         [4, 2, 0, 5],
         [2, 9, 8, 0]],

        [[4, 9, 5, 4],
         [3, 9, 4, 6],
         [2, 3, 0, 4]],

        [[2, 4, 0, 2],
         [6, 9, 1, 6],
         [3, 8, 8, 7]],

        [[6, 9, 4, 4],
         [6, 9, 1, 9],
         [1, 8, 0, 2]]]])

In [155]:
A = np.random.randint(0,10,(3,4,3,4))
print(A)
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[[[0 8 4 7]
   [7 3 5 3]
   [0 4 2 3]]

  [[2 6 3 5]
   [4 5 4 0]
   [8 3 7 4]]

  [[0 0 9 2]
   [8 7 2 0]
   [2 8 5 2]]

  [[2 5 6 0]
   [2 3 1 0]
   [2 9 1 9]]]


 [[[9 1 2 8]
   [6 6 5 5]
   [1 5 4 3]]

  [[1 4 5 4]
   [5 8 4 9]
   [6 5 3 4]]

  [[3 0 7 1]
   [7 7 9 5]
   [6 9 8 1]]

  [[2 9 5 5]
   [1 0 5 5]
   [1 6 1 5]]]


 [[[4 2 9 3]
   [1 2 5 4]
   [0 7 2 4]]

  [[1 0 2 4]
   [4 9 4 3]
   [0 0 9 2]]

  [[5 1 5 4]
   [8 8 8 4]
   [9 9 6 5]]

  [[7 1 6 0]
   [4 3 7 3]
   [8 4 6 9]]]]
[[46 51 45 40]
 [55 58 63 45]
 [43 38 72 58]]
[[46 51 45 40]
 [55 58 63 45]
 [43 38 72 58]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [156]:
# Author: Jaime Fernández del Río

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.2350815  0.38768242 0.33082032 0.46142701 0.44080431 0.37623893
 0.49049988 0.40472892 0.31913843 0.59695262]
0    0.235082
1    0.387682
2    0.330820
3    0.461427
4    0.440804
5    0.376239
6    0.490500
7    0.404729
8    0.319138
9    0.596953
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [159]:
# Author: Mathieu Blondel

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(A)
print(B)
print(np.dot(A, B))
# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

[[0.02601619 0.47617767 0.878809   0.70490351 0.87187576]
 [0.88538833 0.7868968  0.50934381 0.24071582 0.11344858]
 [0.72866306 0.00440662 0.65571965 0.34051343 0.30708085]
 [0.74432944 0.33692214 0.1426506  0.324802   0.81277629]
 [0.50878043 0.85471576 0.87228206 0.04282515 0.71812633]]
[[0.24885793 0.27973718 0.88338091 0.37058343 0.11760355]
 [0.95245136 0.79198091 0.27643017 0.33159372 0.01105682]
 [0.05861488 0.31256777 0.66160292 0.19893673 0.2735806 ]
 [0.70899551 0.14477514 0.10437055 0.59537324 0.83791233]
 [0.9485459  0.33847353 0.98804808 0.87914189 0.47724594]]
[[1.83830929 1.05624806 1.67106102 1.52854927 1.25549621]
 [1.27794958 1.10333674 1.4738568  0.93342063 0.5080136 ]
 [0.75666837 0.56551755 1.41768142 0.87463861 0.69700775]
 [1.51573446 0.84176701 1.68200173 1.32385997 0.79033729]
 [1.70335656 1.34115739 1.97683353 1.3023248  0.68653087]]


array([1.83830929, 1.10333674, 1.41768142, 1.32385997, 0.68653087])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [160]:
# Author: Warren Weckesser

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [161]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [162]:
# Author: Eelco Hoogendoorn

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [163]:
# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 13) ( 0, 49) ( 1, 44) ( 1, 86) ( 5, 32) ( 5, 68) ( 6, 17) ( 6, 79)
 (10, 38) (10, 68) (10, 88) (10, 94) (13, 49) (17, 79) (21, 49) (21, 66)
 (22, 33) (22, 58) (22, 73) (22, 75) (32, 68) (33, 58) (38, 68) (39, 47)
 (39, 97) (44, 86) (47, 97) (49, 66) (73, 75) (88, 94)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [165]:
# Author: Jaime Fernández del Río

C = np.bincount([1,1,2,3,4,4,6])
print(C)
A = np.repeat(np.arange(len(C)), C)
print(A)

[0 2 1 1 2 0 1]
[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [167]:
# Author: Jaime Fernández del Río

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

In [168]:
# Author: Joe Kington / Erik Rigtorp
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [136]:
# Author: Nathaniel J. Smith

Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-6.44122791e-01,  9.76776562e-01, -9.31732266e-02, -8.04335907e-01,
       -9.47595520e-01,  1.59635879e-01, -6.72014786e-01,  7.03030168e-01,
        5.58451750e-02, -7.37757459e-02,  5.41184027e-01,  1.37017635e-01,
        9.96496685e-01, -2.04179047e-01,  4.18417798e-01, -3.30445332e-01,
        8.68730891e-01, -7.08831663e-01,  9.09655318e-01, -5.87427222e-01,
       -5.41353235e-01, -2.65530639e-01,  3.60986779e-01,  4.73948962e-01,
       -6.11312976e-01, -4.59893555e-01,  1.50655912e-01,  8.65546437e-01,
       -4.24313284e-01, -4.81642349e-01, -1.14556771e-01,  1.18531769e-01,
        5.12144564e-01, -9.70707731e-01, -1.11250374e-01,  6.02813553e-01,
        4.51151557e-02, -9.38484852e-01, -8.00431366e-02,  9.74457169e-01,
       -3.77652911e-01, -9.03180239e-01,  3.86806717e-01, -4.79060878e-01,
        7.37293371e-01, -8.53226371e-01,  5.03578709e-01, -5.71800081e-01,
        9.56338283e-01,  8.44593688e-01,  8.38250825e-02, -8.43843220e-01,
        6.72269103e-01,  

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [171]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 0.40211689 12.44175883  4.39218157  4.4555662  16.4425753   6.85880235
  6.04503783  3.3463359   5.97213671  6.27511849]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [175]:
# Author: Italmassov Kuanysh

# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 2.70322823  1.34677359  3.85384906  7.6880483   7.78029864  8.08808612
   3.41294984  6.72130235 12.29099486  4.89675423]
 [ 4.29631623  2.42950882 12.3942343   6.63486527  5.79026048 12.67045135
   4.92918302  4.30119589  1.24088443  4.98357756]
 [ 1.31157907  2.5494078   2.19603363  8.9669305   8.28805129  6.53796216
   5.06883273  8.35847029 12.78742513  6.55501555]
 [11.88466426 17.1117339   4.99373074  4.5805339   3.57799465  4.55517115
  12.49202525 12.13457954  0.84704277 12.02891316]
 [12.3466546  17.71760691  4.98600281  3.92474686  4.50073121  4.83386824
  12.50012608 11.90947669  0.07729178 11.90880053]
 [ 8.28553815  1.5993681  15.57595755  7.26067052  4.1747613  16.45009978
   8.15171528  6.8313112   0.40099036  7.84990317]
 [ 4.717522    8.61216486  2.68362518 10.05012315  5.98524696  0.79560054
  10.00807366 12.28009414 10.44448329 10.97230929]
 [ 7.6237505  12.75185781  1.74819742  4.20806752  1.5535081   0.58272985
   9.19839151  9.64270512  2.89910935  9.15108651]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [176]:
# Author: Nicolas Rougier

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

In [177]:
# Author: Stefan van der Walt

Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [180]:
# Author: Stefan van der Walt

Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(Z)
print(rank)

[[0.62866958 0.24035972 0.01049628 0.96583827 0.0435661  0.74768757
  0.15832574 0.38470808 0.75669097 0.22767249]
 [0.75912145 0.30749013 0.76293131 0.14798865 0.49777021 0.56704551
  0.47210917 0.93477634 0.59546385 0.29145161]
 [0.33036689 0.31409237 0.53662839 0.36870418 0.51817431 0.66559405
  0.21589292 0.49598675 0.30950851 0.6195147 ]
 [0.48082876 0.27333386 0.47864376 0.35772492 0.26365006 0.55765454
  0.07221151 0.73694138 0.98212051 0.66409575]
 [0.93582361 0.12279377 0.20850016 0.89548088 0.27613176 0.51415802
  0.31619906 0.63173957 0.74801087 0.22071811]
 [0.23732543 0.25471941 0.73301081 0.73797287 0.68227112 0.9832191
  0.9748914  0.16911638 0.98411391 0.63480078]
 [0.37406727 0.99687627 0.80664633 0.61359579 0.37882831 0.74174803
  0.81130611 0.95538429 0.65287737 0.70401616]
 [0.55816506 0.96503404 0.77032466 0.8363341  0.64848431 0.31591796
  0.84399562 0.27663057 0.2005481  0.8605121 ]
 [0.10726935 0.89835753 0.04428182 0.35890298 0.71958493 0.46381253
  0.61017698 

#### 83. How to find the most frequent value in an array?

In [182]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z))
print(np.bincount(Z).argmax())

[0 3 3 7 3 4 1 1 0 0 1 6 2 2 8 1 2 4 8 2 1 7 5 6 0 5 0 3 6 8 8 7 4 8 2 7 7
 5 8 4 0 3 3 4 3 7 5 8 0 7]
[7 5 5 7 5 4 3 7 7]
0


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [183]:
# Author: Chris Barker

Z = np.random.randint(0,5,(10,10))
n = 3
print(Z.shape)
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

(10, 10)
[[[[2 0 3]
   [1 1 3]
   [0 1 0]]

  [[0 3 0]
   [1 3 2]
   [1 0 4]]

  [[3 0 4]
   [3 2 4]
   [0 4 1]]

  [[0 4 3]
   [2 4 1]
   [4 1 0]]

  [[4 3 3]
   [4 1 4]
   [1 0 3]]

  [[3 3 0]
   [1 4 0]
   [0 3 0]]

  [[3 0 0]
   [4 0 1]
   [3 0 0]]

  [[0 0 4]
   [0 1 2]
   [0 0 3]]]


 [[[1 1 3]
   [0 1 0]
   [2 2 0]]

  [[1 3 2]
   [1 0 4]
   [2 0 4]]

  [[3 2 4]
   [0 4 1]
   [0 4 0]]

  [[2 4 1]
   [4 1 0]
   [4 0 3]]

  [[4 1 4]
   [1 0 3]
   [0 3 2]]

  [[1 4 0]
   [0 3 0]
   [3 2 0]]

  [[4 0 1]
   [3 0 0]
   [2 0 1]]

  [[0 1 2]
   [0 0 3]
   [0 1 2]]]


 [[[0 1 0]
   [2 2 0]
   [3 0 2]]

  [[1 0 4]
   [2 0 4]
   [0 2 0]]

  [[0 4 1]
   [0 4 0]
   [2 0 0]]

  [[4 1 0]
   [4 0 3]
   [0 0 2]]

  [[1 0 3]
   [0 3 2]
   [0 2 1]]

  [[0 3 0]
   [3 2 0]
   [2 1 4]]

  [[3 0 0]
   [2 0 1]
   [1 4 0]]

  [[0 0 3]
   [0 1 2]
   [4 0 2]]]


 [[[2 2 0]
   [3 0 2]
   [1 1 3]]

  [[2 0 4]
   [0 2 0]
   [1 3 2]]

  [[0 4 0]
   [2 0 0]
   [3 2 1]]

  [[4 0 3]
   [0 0 2]
   [2 1 2]]

  [[0

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

In [184]:
# Author: Eric O. Lebigot
# Note: only works for 2d array and value setting using indices

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 9  8 14  8 13]
 [ 8  5  4 10 10]
 [14  4  8 42  2]
 [ 8 10 42  9  9]
 [13 10  2  9  9]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [185]:
# Author: Stefan van der Walt

p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [187]:
# Author: Robert Kern

Z = np.ones((16,16))
print(Z)
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [188]:
# Author: Nicolas Rougier

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [189]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [190]:
# Author: Stefan Van der Walt

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [191]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


/tmp/ipython-input-191-100570611.py:3: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.records.
  R = np.core.records.fromarrays(Z.T,


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [192]:
# Author: Ryan G.

x = np.random.rand(5e7)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

TypeError: 'float' object cannot be interpreted as an integer

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [205]:
# Author: Gabe Schwartz

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
print(A)
print(B)
C = (A[..., np.newaxis, np.newaxis] == B)
print(C)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[[3 4 3]
 [2 4 1]
 [0 3 1]
 [4 3 2]
 [2 1 1]
 [2 3 4]
 [1 4 4]
 [1 1 1]]
[[4 1]
 [1 4]]
[[[[False False]
   [False False]]

  [[ True False]
   [False  True]]

  [[False False]
   [False False]]]


 [[[False False]
   [False False]]

  [[ True False]
   [False  True]]

  [[False  True]
   [ True False]]]


 [[[False False]
   [False False]]

  [[False False]
   [False False]]

  [[False  True]
   [ True False]]]


 [[[ True False]
   [False  True]]

  [[False False]
   [False False]]

  [[False False]
   [False False]]]


 [[[False False]
   [False False]]

  [[False  True]
   [ True False]]

  [[False  True]
   [ True False]]]


 [[[False False]
   [False False]]

  [[False False]
   [False False]]

  [[ True False]
   [False  True]]]


 [[[False  True]
   [ True False]]

  [[ True False]
   [False  True]]

  [[ True False]
   [False  True]]]


 [[[False  True]
   [ True False]]

  [[False  True]
   [ True False]]

  [[False  True]
   [ True False]]]]
[0 1 2 3 4 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
# Author: Robert Kern

Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [142]:
# Author: Warren Weckesser

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [143]:
# Author: Jaime Fernández del Río

Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [1 0 1]]
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [1 0 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [144]:
# Author: Alex Riley
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[5.02840438e-02, 2.79224711e-01, 3.21283889e-01, 4.66147982e-01,
        4.55023312e-01, 4.69394537e-01, 2.81332870e-03, 3.72899369e-01,
        1.64784536e-01, 1.14319213e-01],
       [2.18171647e-02, 1.21149594e-01, 1.39398167e-01, 2.02251580e-01,
        1.97424825e-01, 2.03660190e-01, 1.22064279e-03, 1.61793013e-01,
        7.14964647e-02, 4.96006470e-02],
       [5.61418394e-03, 3.11752748e-02, 3.58711573e-02, 5.20451483e-02,
        5.08030853e-02, 5.24076242e-02, 3.14106496e-04, 4.16339954e-02,
        1.83980966e-02, 1.27636730e-02],
       [1.91798942e-02, 1.06504967e-01, 1.22547642e-01, 1.77803301e-01,
        1.73560007e-01, 1.79041638e-01, 1.07309084e-03, 1.42235387e-01,
        6.28539339e-02, 4.36048944e-02],
       [3.78518713e-02, 2.10189495e-01, 2.41850008e-01, 3.50898060e-01,
        3.42523840e-01, 3.53341940e-01, 2.11776436e-03, 2.80704132e-01,
        1.24043385e-01, 8.60550547e-02],
       [1.81664452e-02, 1.00877336e-01, 1.16072330e-01, 1.68408328e-01,
   

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [145]:
# Author: Bas Swinckels

phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [146]:
# Author: Evgeni Burovski

X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [147]:
# Author: Jessica B. Hamrick

X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.07027303  0.32963315]
