# 🚀 `reshape` vs `resize` in NumPy

---

# 🏗️ 1️⃣ `reshape`

---

## ✅ What does `reshape` do?

* It returns a **new view (or sometimes a copy) of the original data**, but with a **different shape**.
* It does **not change the original array unless you assign it back**.
* The **total number of elements must remain the same**.

---

## 🖋️ Syntax
array.reshape(newshape, order='C')




* `newshape`: tuple, e.g. `(2, 3)`
* `order`: `'C'` (row-major) or `'F'` (column-major)

---

## 🔥 Example: Basic reshape


In [2]:
import numpy as np

a = np.arange(12)
print(a)
# [ 0  1  2  3  4  5  6  7  8  9 10 11]

b = a.reshape(3, 4)
print(b)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]
b[0] = 1
a


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 1,  1,  1,  1,  4,  5,  6,  7,  8,  9, 10, 11])


✅ Notice `a` is still 1D `(12,)`, while `b` is `(3,4)`.

---

## 🔍 What if shape doesn’t match?


In [3]:
a.reshape(5, 3)


ValueError: cannot reshape array of size 12 into shape (5,3)

In [4]:
a.reshape(2,-1)

array([[ 1,  1,  1,  1,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])


❌ You get an error because `5*3=15` doesn’t match `12`.

---

## ⚡ Using `-1` to auto-calculate

You can ask NumPy to figure out the missing dimension.


In [5]:
c = a.reshape(2, -1)  # 2 * ? = 12 -> ?=6
print(c.shape)  # (2,6)

(2, 6)



---

## 🧭 Changing to higher dimension (3D)


In [7]:
d = a.reshape(2, 3, 2)
print(d)
# [[[ 0  1]
#   [ 2  3]
#   [ 4  5]]
#
#  [[ 6  7]
#   [ 8  9]
#   [10 11]]]


[[[ 1  1]
  [ 1  1]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]



---

## 🚀 Important note

* `reshape` tries to return a **view (no extra memory)** if possible.
* But if necessary (e.g. non-contiguous slice), it makes a **copy**.

---

# 🏗️ 2️⃣ `resize`

---

## ✅ What does `resize` do?

It depends on **which version** you use:

---

### 🚀 A. `arr.resize(newshape)` (method)

* Changes the array **in-place**.
* Can change the total size:

  * If the new shape is larger, fills new values with `0` (or `nan` for floats).
  * If smaller, truncates.

---

## 🔥 Example: resize (method)


In [8]:
a = np.arange(6)
print(a)
# [0 1 2 3 4 5]

a.resize((2,3))
print(a)
# [[0 1 2]
#  [3 4 5]]


[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]



---

### ✅ Resize to a larger shape


In [9]:
a.resize((3,4)) 


In [10]:
print(a)
# [[0 1 2 3]
#  [4 5 0 0]
#  [0 0 0 0]]


[[0 1 2 3]
 [4 5 0 0]
 [0 0 0 0]]



✅ Fills extra with `0`.

---

## ⚠️ Typical error with `resize`:


In [15]:
b

array([[0, 1, 2, 3],
       [0, 0, 0, 0]])

In [17]:
b = a[::2]
# b
b.resize(3,3)


ValueError: resize only works on single-segment arrays

Because `b` shares data with `a`.

You can force it:

In [14]:
b.resize((3,3),refcheck=False)


ValueError: resize only works on single-segment arrays


But be careful — may break references.

---

## 🚀 B. `np.resize(array, newshape)` (function)

* Always returns a **new array**.
* Repeats data if needed to fill the shape.

---

### 🔥 Example: `np.resize`

```python
a = np.array([1,2,3])
b = np.resize(a, (2,4))
print(b)
# [[1 2 3 1]
#  [2 3 1 2]]
```

✅ Fills by **cycling through the original data.**

---

# ✅ 🔬 Summary comparison

| Feature               | `reshape`                | `arr.resize` (method)       | `np.resize` (function)   |
| --------------------- | ------------------------ | --------------------------- | ------------------------ |
| Changes shape?        | ✅ Yes                    | ✅ Yes                       | ✅ Yes                    |
| Keeps total elements? | ✅ Must be same           | ❌ Can change (pads or cuts) | ❌ Can change (repeats)   |
| In-place?             | ❌ No (returns view/copy) | ✅ Yes (modifies itself)     | ❌ No (returns new array) |
| Fills new data?       | ❌ Error if mismatch      | ✅ Pads with `0`             | ✅ Repeats data to fill   |

---

# 🥇 Quick cheat sheet

```python
import numpy as np

a = np.arange(6)

# reshape: same total elements
b = a.reshape(2,3)

# resize (method): modifies a itself
a.resize((3,4))  # fills with 0 if needed

# np.resize (function): returns new array, repeats data
c = np.resize(b, (3,4))
```

🔥 Awesome — let’s take it to the **next level** with some **advanced, deeper insights and tricks** around `reshape` vs `resize` in **NumPy**, including:

✅ multi-dimensional reshaping,
✅ Fortran vs C order,
✅ memory layout & strides,
✅ flatten vs ravel vs reshape,
✅ unusual uses like adding axes and reshaping for broadcasting.

---

# 🚀 Advanced `reshape` vs `resize` concepts in NumPy

---

## ⚙️ 1️⃣ Memory order: `order='C'` vs `order='F'`

### ✅ `order` parameter

* `'C'` = **row-major order** (default, like C arrays).
* `'F'` = **column-major order** (like Fortran / MATLAB).

This changes how numpy reads the data into the reshaped array.

---

### 🔥 Example

```python
import numpy as np

a = np.arange(6).reshape(2,3)
print(a)
# [[0 1 2]
#  [3 4 5]]

# reshape with Fortran order
b = a.reshape(3,2, order='F')
print(b)
# [[0 4]
#  [3 1]
#  [2 5]]
```

✅ It reads **column-wise first**, not row-wise.

---

## 🚀 2️⃣ `flatten` vs `ravel` vs `reshape(-1)`

---

### ✅ `flatten()`

* Always returns a **copy** of data.

```python
a = np.arange(6).reshape(2,3)
f = a.flatten()
f[0] = 99
print(a[0,0])  # still 0
```

---

### ✅ `ravel()`

* Returns a **view if possible** (faster, no new memory). Falls back to a copy if needed.

```python
r = a.ravel()
r[0] = 99
print(a[0,0])  # 99 if contiguous
```

---

### ✅ `reshape(-1)`

* Often equivalent to `ravel()`.

```python
r2 = a.reshape(-1)
```

Also returns a **view if possible**.

---

### ⚠️ Differences example

```python
b = a.T  # transpose
r = b.ravel()  # may still be view
f = b.flatten() # always copy
```

---

## 🔬 3️⃣ Strides and reshaping

### ✅ What are strides?

* Strides tell **how many bytes to jump** in memory to move to the next element along each axis.

```python
a = np.arange(12).reshape(3,4)
print(a.strides)
# (32, 8) on a 64-bit machine: 4 bytes * 8 = 32
```

---

### 🔥 Why does this matter?

* `reshape` tries to create a **view by modifying shape & strides**, without moving data.
* But some operations (e.g. non-contiguous slices) force it to make a copy.

---

### Example of forcing a copy

```python
b = a[:, ::2]  # take every second column
print(b.shape)  # (3,2)

c = b.reshape(-1)  # actually makes a copy
```

Because the data is **not contiguous**.

---

## 🚀 4️⃣ Resize to unusual shapes for broadcasting

---

### 🔥 Adding dimensions with reshape

```python
a = np.arange(3)
print(a.shape)  # (3,)

# reshape to (3,1) to enable broadcasting with (1,3)
b = a.reshape(3,1)
print(b.shape)  # (3,1)
```

---

### ✅ Example: broadcasting outer sum

```python
x = np.arange(3).reshape(3,1)  # shape (3,1)
y = np.arange(4).reshape(1,4)  # shape (1,4)

z = x + y
print(z)
# shape (3,4) result
```

---

## ⚡ 5️⃣ More advanced `np.resize`

### ✅ Repeats data in order to fill shape

```python
a = np.array([1,2,3])
b = np.resize(a, (2,4))
print(b)
# [[1 2 3 1]
#  [2 3 1 2]]
```

It literally cycles the data to fill the target shape.

---

## 🚀 6️⃣ Using `resize` with `refcheck`

When you use the **method** `arr.resize`, it checks for references:

```python
a = np.arange(6)
b = a[::2]
a.resize((3,3))
# ValueError: cannot resize because b references a
```

---

### ✅ Forcing it

```python
a.resize((3,3), refcheck=False)
```

**DANGER**: breaks safety checks — any other views may see garbage.

---

# 🎯 ✅ Summary of advanced differences

| Operation              | Memory                      | Copies data?              | Can change total elements? |
| ---------------------- | --------------------------- | ------------------------- | -------------------------- |
| `reshape`              | reshapes view using strides | ❌ if contiguous, ✅ if not | ❌ Must match               |
| `flatten`              | always 1D copy              | ✅ always                  | ❌                          |
| `ravel`                | tries view, fallback copy   | ❌ / ✅                     | ❌                          |
| `arr.resize` (method)  | modifies in-place           | ✅ changes data            | ✅ pads/truncates           |
| `np.resize` (function) | new array                   | ✅ repeats data            | ✅ cycles                   |

---

# 🚀 🚀 Short advanced examples



In [ ]:

import numpy as np

a = np.arange(12).reshape(3,4)
print(a)
print(a.T.reshape(-1))  # careful, often needs copy
print(a.reshape(4,3, order='F'))  # column-wise fill
print(np.resize(a, (5,5)))  # repeats data


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  4  8  1  5  9  2  6 10  3  7 11]
[[ 0  5 10]
 [ 4  9  3]
 [ 8  2  7]
 [ 1  6 11]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11  0  1  2]
 [ 3  4  5  6  7]
 [ 8  9 10 11  0]]


## Conversion of Dimension

### Reshaping : 1-D to 2D 

In [23]:
# importing numpy
import numpy as np

# creating a numpy array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

# printing array
print("Array : " + str(array))

# length of array
n = array.size

# N-D array N dimension
N = 4

# calculating M
M = n//N

# reshaping numpy array
# converting it to 2-D from 1-D array
reshaped1 = array.reshape(N, M)

# printing reshaped array
print("First Reshaped Array : ")
print(reshaped1)

# creating another reshaped array
reshaped2 = np.reshape(array, (2, 8))

# printing reshaped array
print("Second Reshaped Array : ")
print(reshaped2)

Array : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
First Reshaped Array : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Second Reshaped Array : 
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


### Reshaping : 1-D to 3-D 

In [24]:
# importing numpy
import numpy as np

# creating a numpy array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

# printing array
print("Array : " + str(array))


# reshaping numpy array
# converting it to 3-D from 1-D array
reshaped = array.reshape(2, 2, 4)

# printing reshaped array
print("Reshaped 3-D Array : ")
print(reshaped)

Array : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Reshaped 3-D Array : 
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


## Reshaping N-D to 1-D array 

In [26]:
# importing numpy
import numpy as np

# creating a numpy array
array = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# printing array
print(" 2-D Array : ")
print(array)


# reshaping numpy array
# converting it to 1-D from 2-D array
reshaped = array.reshape((9))

# or we can use unknown dimension
# reshaped = array.reshape((-1))

# printing reshaped array
print("Reshaped 1-D Array : ")
print(reshaped)

 2-D Array : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped 1-D Array : 
[1 2 3 4 5 6 7 8 9]


### Reshaping using unknown dimension 

In [27]:
# importing numpy
import numpy as np

# creating a numpy array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

# printing array
print("Array : " + str(array))


# reshaping numpy array
# converting it to 3-D from 1-D array
reshaped1 = array.reshape((2, 2, -1))

# printing reshaped array
print("First Reshaped Array : ")
print(reshaped1)


# converting it to 2-D array
reshaped2 = array.reshape((4, -1))

# printing reshaped array
print("Second Reshaped Array : ")
print(reshaped2)

Array : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
First Reshaped Array : 
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
Second Reshaped Array : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### Errors Occur during reshaping 

In [28]:
# importing numpy
import numpy as np

# creating a numpy array
array = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# printing array
print(" 2-D Array : ")
print(array)


# reshaping numpy array
# converting it to 1-D from 2-D array
# reshaping it into 1, 5
reshaped = array.reshape((1, 5))

# or we can use 

# printing reshaped array
print("Reshaped 1-D Array : ")
print(reshaped)

 2-D Array : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


ValueError: cannot reshape array of size 9 into shape (1,5)

| Feature            | `reshape`                 | `resize`                 |
| ------------------ | ------------------------- | ------------------------ |
| Modifies original? | 🚫 No (returns new array) | ✅ Yes (changes in-place) |
| Keeps data?        | ✅ Always                  | ⚠ May fill               |
