# 📚 1. Stacking in NumPy

Stacking is about **joining multiple arrays into a single array** along a new axis or an existing axis.

NumPy provides different functions to achieve this, depending on:

* Whether you want to stack **horizontally**, **vertically**, or along **depth (third axis)**.
* Whether you want to **add a new axis** or join along an **existing axis**.

---

## 🔹 1.1 Types of stacking

### ➡️ `np.vstack` (Vertical stack)

* Stacks arrays **on top of each other** (along rows).
* Increases the number of rows.




In [2]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Convert to 2D row vectors for stacking
a = a.reshape(1, 3)
b = b.reshape(1, 3)
print(a)
print(b)
vstacked = np.vstack((a, b))
print(vstacked)


[[1 2 3]]
[[4 5 6]]
[[1 2 3]
 [4 5 6]]



📌 Output:

```
[[1 2 3]
 [4 5 6]]
```

---

### ➡️ `np.hstack` (Horizontal stack)

* Stacks arrays **side by side** (along columns).
* Increases the number of columns.

```python
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

hstacked = np.hstack((a, b))
print(hstacked)
```

📌 Output:

```
[[1 4]
 [2 5]
 [3 6]]
```

---

### ➡️ `np.dstack` (Depth stack)

* Stacks along the **third axis (depth)**.

```python
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

dstacked = np.dstack((a, b))
print(dstacked)
```

📌 Output:

```
[[[1 5]
  [2 6]]
 
 [[3 7]
  [4 8]]]
```

Here you have shape `(2, 2, 2)` — a kind of "stack of matrices".

---

### ➡️ `np.stack` (General stacking along new axis)

* Allows stacking along **any new axis** you specify.

```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack along new axis 0
stacked_0 = np.stack((a, b), axis=0)
print(stacked_0)  # shape (2, 3)

# Stack along new axis 1
stacked_1 = np.stack((a, b), axis=1)
print(stacked_1)  # shape (3, 2)
```

📌 Output:

```
[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]
```

---

### ➡️ `np.column_stack` and `np.row_stack`

* `np.column_stack` stacks 1D arrays as columns.
* `np.row_stack` stacks like `vstack`.

```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

col_stack = np.column_stack((a, b))
print(col_stack)
```

📌 Output:

```
[[1 4]
 [2 5]
 [3 6]]
```

---

# ✂️ 2. Splitting in NumPy

Splitting is about **breaking one array into multiple smaller arrays**.

---

## 🔹 2.1 Types of splitting

### ➡️ `np.hsplit` (Horizontal split)

* Split along columns.

```python
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

hsplitted = np.hsplit(a, 2)  # Split into 2
print(hsplitted)
```

📌 Output:

```
[array([[1, 2],
       [5, 6]]), 
 array([[3, 4],
       [7, 8]])]
```

---

### ➡️ `np.vsplit` (Vertical split)

* Split along rows.

```python
vsplitted = np.vsplit(a, 2)
print(vsplitted)
```

📌 Output:

```
[array([[1, 2, 3, 4]]), 
 array([[5, 6, 7, 8]])]
```

---

### ➡️ `np.dsplit` (Depth split)

* Split along the third axis.

```python
b = np.dstack((a, a))  # shape (2,4,2)
dsplitted = np.dsplit(b, 2)
print(dsplitted)
```

---

### ➡️ `np.split`

* A general split you can use along any axis.

```python
c = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

splitted = np.split(c, 2, axis=1)
print(splitted)
```

📌 Output:

```
[array([[1, 2],
       [5, 6]]), 
 array([[3, 4],
       [7, 8]])]
```

---

# 💡 Summary table

| Function          | What it does                     |
| ----------------- | -------------------------------- |
| `np.vstack`       | stack arrays vertically (rows)   |
| `np.hstack`       | stack arrays horizontally (cols) |
| `np.dstack`       | stack arrays along depth         |
| `np.stack`        | stack along new specified axis   |
| `np.column_stack` | stack as columns                 |
| `np.row_stack`    | stack as rows (like vstack)      |

| Function    | What it does                 |
| ----------- | ---------------------------- |
| `np.hsplit` | split along columns          |
| `np.vsplit` | split along rows             |
| `np.dsplit` | split along depth            |
| `np.split`  | general split along any axis |

---

# 🚀 Visualization intuition

Imagine these as stacking/splitting papers:

* 📚 `vstack` — placing sheets one over another to make a pile.
* 📃 `hstack` — placing sheets side by side to make a long strip.
* 🎂 `dstack` — stacking sheets to make layers of a cake.
* ✂️ `split` — cutting the sheet into smaller strips either horizontally or vertically.

