# 🚀 What is broadcasting in NumPy?

✅ **Broadcasting** is a way for NumPy to perform **element-wise operations on arrays of different shapes** without explicitly copying data.

It **"stretches" smaller arrays across larger ones** so that arithmetic operations can be performed efficiently.

It avoids making many copies of data and speeds up computation.

---

# 📚 Why is it needed?

In NumPy, when you do operations like

```python
A + B
```

it normally requires `A` and `B` to have the **same shape**.

But with broadcasting, if `A` and `B` have **compatible shapes**, NumPy automatically expands the smaller array to match the bigger one *virtually*, without making unnecessary copies.

---

# 🔍 The broadcasting rules

NumPy compares arrays' shapes **from right to left (trailing dimensions)**.

It allows two dimensions to be compatible when:

| Condition                                       | Meaning                                |
| ----------------------------------------------- | -------------------------------------- |
| They are equal                                  | e.g. (3, 4) and (3, 4)                 |
| Or one of them is `1`                           | e.g. (3, 4) and (1, 4) or (3, 1)       |
| Or the dimension doesn't exist (treated as `1`) | e.g. (3, 4) and (4,) treated as (1, 4) |

---

### ➡️ In short

```
Two dimensions are compatible if they are equal or one of them is 1.
```

---

# ⚙️ Examples of broadcasting

---

## ✅ Example 1: simple scalar broadcasting


In [3]:
import numpy as np

A = np.array([1, 2, 3])
print(A + 10)


[11 12 13]




➡️ Here `10` is treated as if it were `[10, 10, 10]`.

Output:

```
[11 12 13]
```

---

## ✅ Example 2: 1D and 2D


In [4]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])
print(A + B)


[[11 22 33]
 [14 25 36]]




* `A.shape = (2, 3)`
* `B.shape = (3,)` → treated as `(1, 3)`

So it stretches along the first dimension (rows).

Output:

```
[[11 22 33]
 [14 25 36]]
```

---

## ✅ Example 3: adding column vector to matrix


In [5]:
C = np.array([[1],
              [2],
              [3]])

D = np.array([10, 20, 30])
print(C + D)


[[11 21 31]
 [12 22 32]
 [13 23 33]]




* `C.shape = (3, 1)`
* `D.shape = (3,)` → treated as `(1, 3)`

So broadcasting gives final shape `(3, 3)`.

Output:

```
[[11 21 31]
 [12 22 32]
 [13 23 33]]
```

---

# ❌ When broadcasting fails

If shapes are incompatible, NumPy raises a `ValueError`.

Example:


In [11]:
# A = np.array([1, 2, 3])
# B = np.array([10, 20])
# A + B


* `A.shape = (3,)`
* `B.shape = (2,)`

No dimension is `1`, so incompatible.

---

# 🧠 Broadcasting by aligning shapes

You can think of broadcasting like **aligning shapes to the right** and **stretching 1s**.

| Example          | Shape alignment |
| ---------------- | --------------- |
| A: `(3, 4, 5)`   | `(3, 4, 5)`     |
| B: `(     4, 1)` | `(1, 4, 1)`     |

Result shape will be `(3, 4, 5)`.

---

# 💥 Why broadcasting is powerful?

✅ It avoids explicit loops and manual `tile` or `repeat` calls.

So instead of writing slow code like:


In [10]:
A

array([1, 2, 3])

In [9]:
# for i in range(len(A)):
#     C[i] = A[i] + B


you just write:

```python
C = A + B
```

and NumPy automatically broadcasts, making it very fast (vectorized).

---

# 🚀 Summary table of broadcasting

| Shapes                    | Result shape | Works because                       |
| ------------------------- | ------------ | ----------------------------------- |
| `(3, 4)` + `(4,)`         | `(3, 4)`     | second dimension matches            |
| `(5, 1)` + `(4,)`         | `(5, 4)`     | `1` expands to `4`                  |
| `(3, 1, 4)` + `(   2, 1)` | `(3, 2, 4)`  | middle `1` expands to `2`           |
| `(3, 4)` + `(2, 4)`       | ❌ error      | first dims `3` and `2` incompatible |

In [13]:
np.array([[1, 2], [3, 4]]).shape
np.array([10, 20]).shape

(2,)