In [1]:
import numpy as np

# Matrix creation
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
x = np.array([1, 2])

# Element-wise operations
print("A + B:\n", A + B)
print("A - B:\n", A - B)
print("A * B (element-wise):\n", A * B)
print("A / B:\n", A / B)
print("A squared:\n", A ** 2)

# Matrix multiplication (dot product)
print("A @ B (matrix multiplication):\n", A @ B)
print("np.dot(A, B):\n", np.dot(A, B))

# Transpose
print("Transpose of A:\n", A.T)

# Reshape & flatten
print("A reshaped to (4,1):\n", A.reshape(4,1))
print("A flattened:\n", A.flatten())

# Inverse, determinant
print("Inverse of A:\n", np.linalg.inv(A))
print("Determinant of A:", np.linalg.det(A))

# Solve linear system Ax = b
print("Solution to Ax = x:", np.linalg.solve(A, x))

# Eigenvalues & eigenvectors
eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)

# Singular Value Decomposition
U, S, Vt = np.linalg.svd(A)
print("SVD U:\n", U)
print("SVD S:", S)
print("SVD Vt:\n", Vt)

# Norm & trace
print("Frobenius norm:", np.linalg.norm(A))
print("Trace (sum of diagonal):", np.trace(A))

# Diagonal operations
print("Extract diagonal:", np.diag(A))
print("Create diagonal matrix:", np.diag([10, 20]))

# Upper & lower triangular
print("Upper triangle:\n", np.triu(A))
print("Lower triangle:\n", np.tril(A))

# Outer & inner product
print("Outer product of x and itself:\n", np.outer(x, x))
print("Inner product (dot) of x with itself:", np.inner(x, x))


A + B:
 [[ 6  8]
 [10 12]]
A - B:
 [[-4 -4]
 [-4 -4]]
A * B (element-wise):
 [[ 5 12]
 [21 32]]
A / B:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
A squared:
 [[ 1  4]
 [ 9 16]]
A @ B (matrix multiplication):
 [[19 22]
 [43 50]]
np.dot(A, B):
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]
A reshaped to (4,1):
 [[1]
 [2]
 [3]
 [4]]
A flattened:
 [1 2 3 4]
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant of A: -2.0000000000000004
Solution to Ax = x: [0.  0.5]
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
SVD U:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
SVD S: [5.4649857  0.36596619]
SVD Vt:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]
Frobenius norm: 5.477225575051661
Trace (sum of diagonal): 5
Extract diagonal: [1 4]
Create diagonal matrix: [[10  0]
 [ 0 20]]
Upper triangle:
 [[1 2]
 [0 4]]
Lower triangle:
 [[1 0]
 [3 4]]
Outer product of x and itself:
 [[1 2]
 [2 4]]
Inner product 

In [2]:
import numpy as np

# Matrix creation
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
x = np.array([1, 2])

# Element-wise operations
print("A + B:\n", A + B)
print("A - B:\n", A - B)
print("A * B:\n", A * B)
print("A / B:\n", A / B)
print("A squared:\n", A ** 2)

# Matrix multiplication
print("A @ B:\n", A @ B)
print("np.dot(A, B):\n", np.dot(A, B))

# Transpose
print("Transpose of A:\n", A.T)

# Inverse, determinant, rank
print("Inverse of A:\n", np.linalg.inv(A))
print("Determinant of A:", np.linalg.det(A))
print("Rank of A:", np.linalg.matrix_rank(A))

# Solve Ax = b
print("Solution to Ax = b:", np.linalg.solve(A, x))

# Eigenvalues & eigenvectors
eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)

# Singular Value Decomposition
U, S, Vt = np.linalg.svd(A)
print("U:\n", U)
print("Singular values:", S)
print("Vt:\n", Vt)

# QR decomposition
Q, R = np.linalg.qr(A)
print("Q:\n", Q)
print("R:\n", R)

# Cholesky decomposition
try:
    L = np.linalg.cholesky(A @ A.T)
    print("Cholesky factor L:\n", L)
except np.linalg.LinAlgError:
    print("Matrix not positive definite for Cholesky")

# Norms & trace
print("Norm of A:", np.linalg.norm(A))
print("Trace of A:", np.trace(A))

# Outer & inner products
print("Outer product:\n", np.outer(x, x))
print("Inner product:", np.inner(x, x))

# Diagonal operations
print("Diagonal of A:", np.diag(A))
print("Matrix from diagonal:", np.diag([10, 20]))

# Upper & lower triangular
print("Upper triangle:\n", np.triu(A))
print("Lower triangle:\n", np.tril(A))


A + B:
 [[ 6  8]
 [10 12]]
A - B:
 [[-4 -4]
 [-4 -4]]
A * B:
 [[ 5 12]
 [21 32]]
A / B:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
A squared:
 [[ 1  4]
 [ 9 16]]
A @ B:
 [[19 22]
 [43 50]]
np.dot(A, B):
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant of A: -2.0000000000000004
Rank of A: 2
Solution to Ax = b: [0.  0.5]
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
U:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Singular values: [5.4649857  0.36596619]
Vt:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]
Q:
 [[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
R:
 [[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]
Cholesky factor L:
 [[2.23606798 0.        ]
 [4.91934955 0.89442719]]
Norm of A: 5.477225575051661
Trace of A: 5
Outer product:
 [[1 2]
 [2 4]]
Inner product: 5
Diagonal of A: [1 4]
Matrix from diagonal: [[10  0]
 [ 0 20]]
Up