# ✅ Basic NumPy API

In [1]:

import numpy as np

# From lists
a = np.array([1, 2, 3])
print("Array from list:", a)

# Zeros, ones, full
z = np.zeros((2, 3))
o = np.ones(4)
f = np.full((2,2), 7)
I = np.eye(3)
r = np.arange(0, 10, 2)
l = np.linspace(0, 1, 5)

print("Zeros:\n", z)
print("Ones:", o)
print("Full:\n", f)
print("Identity:\n", I)
print("Arange:", r)
print("Linspace:", l)


Array from list: [1 2 3]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones: [1. 1. 1. 1.]
Full:
 [[7 7]
 [7 7]]
Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]


In [2]:

# Basic arithmetic and broadcasting
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

print("x + y =", x + y)
print("x * 2 =", x * 2)
print("np.sqrt(x):", np.sqrt(x))


x + y = [11 22 33]
x * 2 = [2 4 6]
np.sqrt(x): [1.         1.41421356 1.73205081]


In [3]:

# Basic statistics
a = np.random.randn(5, 4)
print("Mean:", np.mean(a))
print("Std:", np.std(a))
print("Min:", np.min(a))
print("Argmax (index):", np.argmax(a))


Mean: -0.25278547059297146
Std: 1.2878708330696904
Min: -3.6345308375743284
Argmax (index): 8


In [4]:

# Reshape and transpose
b = np.arange(12).reshape(3,4)
print("Reshaped array:\n", b)
print("Transposed:\n", b.T)


Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transposed:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


# ✅ Intermediate NumPy API

In [5]:

# Where, conditional logic
a = np.array([1, 2, 3, 4])
result = np.where(a > 2, 10, -1)
print(result)


[-1 -1 10 10]


In [6]:

# Meshgrid
x = np.linspace(0, 1, 3)
y = np.linspace(0, 1, 2)
X, Y = np.meshgrid(x, y)
print("X grid:\n", X)
print("Y grid:\n", Y)


X grid:
 [[0.  0.5 1. ]
 [0.  0.5 1. ]]
Y grid:
 [[0. 0. 0.]
 [1. 1. 1.]]


In [7]:

# Repeat and tile
print("Repeat:", np.repeat([1,2], 3))
print("Tile:", np.tile([1,2], 3))


Repeat: [1 1 1 2 2 2]
Tile: [1 2 1 2 1 2]


In [8]:

# Histogram & bincount
data = np.random.randint(0, 5, size=20)
hist, bins = np.histogram(data, bins=5)
counts = np.bincount(data)
print("Histogram:", hist)
print("Bins:", bins)
print("Bincount:", counts)


Histogram: [3 4 2 5 6]
Bins: [0.  0.8 1.6 2.4 3.2 4. ]
Bincount: [3 4 2 5 6]


In [9]:

# Cumsum, diff, gradient
arr = np.array([1,2,4,7])
print("Cumsum:", np.cumsum(arr))
print("Diff:", np.diff(arr))
print("Gradient:", np.gradient(arr))


Cumsum: [ 1  3  7 14]
Diff: [1 2 3]
Gradient: [1.  1.5 2.5 3. ]


In [10]:

# Insert, delete, unique
arr = np.array([1,2,2,3,3,3])
print("Unique with counts:", np.unique(arr, return_counts=True))
new = np.insert(arr, 2, 99)
deleted = np.delete(arr, [0,1])
print("After insert:", new)
print("After delete:", deleted)


Unique with counts: (array([1, 2, 3]), array([1, 2, 3]))
After insert: [ 1  2 99  2  3  3  3]
After delete: [2 3 3 3]


# ✅ Advanced NumPy API

In [11]:

# Broadcasting with newaxis
a = np.array([1,2,3])
b = a[:, np.newaxis]
print("Shape a:", a.shape)
print("Shape b:", b.shape)
print("Broadcast sum:\n", a + b)


Shape a: (3,)
Shape b: (3, 1)
Broadcast sum:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [12]:

# Einsum
A = np.arange(9).reshape(3,3)
print("Trace using einsum:", np.einsum('ii->', A))
x = np.array([1,2,3])
y = np.array([4,5,6])
print("Dot product:", np.einsum('i,i->', x, y))


Trace using einsum: 12
Dot product: 32


In [13]:

# Masked arrays
import numpy.ma as ma
masked = ma.masked_array([1,2,3,-1], mask=[0,0,0,1])
print("Mean ignoring masked:", masked.mean())


Mean ignoring masked: 2.0


In [14]:

# Vectorize
def myfunc(x):
    return x**2 if x > 0 else 0

vfunc = np.vectorize(myfunc)
print(vfunc(np.array([-2, -1, 0, 1, 2])))


[0 0 0 1 4]


In [15]:

# Linear algebra
M = np.array([[2,3], [5,7]])
invM = np.linalg.inv(M)
detM = np.linalg.det(M)
U, S, V = np.linalg.svd(M)
print("Inverse:\n", invM)
print("Determinant:", detM)
print("SVD -> U:\n", U)


Inverse:
 [[-7.  3.]
 [ 5. -2.]]
Determinant: -0.9999999999999987
SVD -> U:
 [[-0.38643579 -0.92231631]
 [-0.92231631  0.38643579]]


In [16]:

# Padding
arr = np.array([[1,2],[3,4]])
padded = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("Padded array:\n", padded)


Padded array:
 [[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]


In [17]:

# Memmap
fp = np.memmap('mymemmap.dat', dtype='float32', mode='w+', shape=(1000,1000))
fp[0,0] = 123
print("Memmap value:", fp[0,0])


Memmap value: 123.0
